server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Database settings.
database:
    # the businessName of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: panallyadmin
    # the password
    password: Panally090117
    # the JDBC URL; the database is called hello_world
    url: jdbc:mysql://panally.cinqufhfwblf.ap-south-1.rds.amazonaws.com:3306/panally
    # the SQL query to run when validating a connection's liveness
    validationQuery: "/* MyService Health Check */ SELECT 1"
